[package]
name = "bevy_trenchbroom"
description = "Bevy integration with TrenchBroom"
version = "0.2.0"
edition = "2021"
authors = [ "Noxmore" ]
repository = "https://github.com/Noxmore/bevy_trenchbroom"
readme = "readme.md"
license = "MIT OR Apache-2.0"
categories = [ "game-development" ]
exclude = [ "assets" ]

[dependencies]
anyhow = "1.0"
bevy = { version = "0.13", default-features = false, features = [
    "bevy_asset",
    "bevy_render",
    "bevy_pbr",
    "serialize",
] }
bevy_reflect = { version = "0.13", features = ["documentation"] }
bevy_rapier3d = { version = "0.25", features = ["serde"], optional = true }
default-struct-builder = "0.5.0"
float-ord = "0.3"
image = "0.24"
indexmap = { version = "2.2", features = ["serde"] }
itertools = "0.12"
json = "0.12"
lazy_static = "1.4"
quake-util = { version = "0.3.2", features = ["std", "hashbrown"] }
ron = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
smart-default = "0.7"
thiserror = "1.0"
toml = "0.8"

[dev-dependencies.bevy]
version = "0.13"
features = ["bevy_scene"]

[features]
rapier = [ "dep:bevy_rapier3d" ]
