[package]
name = "bevy_trenchbroom"
description = "Bevy integration with TrenchBroom"
version = "0.5.1"
edition = "2021"
authors = ["Noxmore"]
repository = "https://github.com/Noxmore/bevy_trenchbroom"
readme = "readme.md"
license = "MIT OR Apache-2.0"
categories = ["game-development"]
exclude = ["assets"]

[dependencies]
anyhow = "1.0"
bevy = { version = "0.14", default-features = false, features = [
    "bevy_asset",
    "bevy_render",
    "bevy_pbr",
] }
bevy_reflect = { version = "0.14", features = ["documentation"] }
bevy_rapier3d = { version = "0.27", optional = true }
avian3d = { version = "0.1", optional = true }
default-struct-builder = "0.5.0"
float-ord = "0.3"
image = "0.25"
indexmap = { version = "2.2", features = ["serde"] }
itertools = "0.13"
json = "0.12"
quake-util = { version = "0.3.2", features = ["std", "hashbrown"] }
serde = { version = "1.0", features = ["derive"] } # serde isn't optional because MaterialProperties requires to be deserialized
thiserror = "2.0"
toml = "0.8"
disjoint-sets = "0.4.2"
q1bsp = { git = "https://github.com/Noxmore/q1bsp.git", rev = "2f6665b" }
# q1bsp = { path = "/d/_dev/_lib/rust/q1bsp" } # TODO tmp
nil = "0.13"
imageproc = "0.25.0" # TODO tmp
fastrand = "2.2.0" # TODO tmp
# bytemuck = "1.20.0"
# encase = { version = "0.10.0", features = ["glam"] }

[dev-dependencies.bevy]
version = "0.14"
features = ["bevy_scene"]

[dev-dependencies]
bevy_flycam = "0.14"
bevy-inspector-egui = "0.27" # TODO TMP

[features]
rapier = ["dep:bevy_rapier3d"]
avian = ["dep:avian3d"]
