[workspace]
members = [
	"macros",
]

[workspace.package]
version = "0.6.4"
description = "TrenchBroom and ericw-tools integration with Bevy"
edition = "2021"
authors = ["Noxmore"]
repository = "https://github.com/Noxmore/bevy_trenchbroom"
license = "MIT OR Apache-2.0"

[package]
name = "bevy_trenchbroom"
readme = "readme.md"
categories = ["game-development"]
exclude = ["assets"]

description.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bevy_trenchbroom_macros = { version = "0.6.4", path = "macros" }

anyhow = "1.0"
bevy = { version = "0.15", default-features = false, features = [
	"bevy_asset",
	"bevy_scene",
	"bevy_render",
] }
bevy_reflect = { version = "0.15", features = ["documentation"] }
bevy_materialize = { version = "^0.4.1", default-features = false, features = ["toml"] }
bevy_rapier3d = { version = "0.29", optional = true }
avian3d = { version = "0.2", optional = true }
default-struct-builder = "0.5.0"
float-ord = "0.3"
image = { version = "0.25", default-features = false }
itertools = "0.14"
json = "0.12"
quake-util = { version = "0.3.2", features = ["std", "hashbrown"] }
serde = { version = "1", features = ["derive"] } # serde isn't optional because bevy_materialize requires it anyway
thiserror = "2.0"
disjoint-sets = "0.4.2"
qbsp = { version = "0.3", features = ["bevy_reflect", "serde"] }
nil = "0.14"
ndshape = "0.3.0"
inventory = { version = "0.3", optional = true }
strum = { version = "0.27", features = ["derive"] }
enumflags2 = "0.7"

[dev-dependencies]
bevy = { version = "0.15", default-features = true }
bevy_flycam = "0.15"
bevy-inspector-egui = "0.29"

[[example]]
name = "bsp_loading"
required-features = ["bevy_pbr", "auto_register"]

[[example]]
name = "map_loading"
required-features = ["bevy_pbr", "auto_register"]

[features]
default = ["bevy_pbr", "auto_register"]
bevy_pbr = ["bevy/bevy_pbr", "bevy_materialize/bevy_pbr"]
rapier = ["dep:bevy_rapier3d"]
avian = ["dep:avian3d"]
auto_register = ["dep:inventory", "bevy_trenchbroom_macros/auto_register"]
